name: Rust
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR:  always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config zip

      - name: Build (release)
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Package release artifact
        run: |
          mkdir -p release
          zip -j release/bentobox-${{ github.run_number }}-linux-x86_64.zip target/release/bentobox

      - name: Create Release (attach artifact)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
